---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: UserApp
  labels:
    app: UserApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserApp
  template:
    metadata:
      labels:
        app: UserApp
    spec:
      containers:
        - name: UserApp
          image: username/UserApp:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: point
  labels:
    app: point
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point
  template:
    metadata:
      labels:
        app: point
    spec:
      containers:
        - name: point
          image: username/point:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agreement
  labels:
    app: agreement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agreement
  template:
    metadata:
      labels:
        app: agreement
    spec:
      containers:
        - name: agreement
          image: username/agreement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Benefits
  labels:
    app: Benefits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Benefits
  template:
    metadata:
      labels:
        app: Benefits
    spec:
      containers:
        - name: Benefits
          image: username/Benefits:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: UserApp
  labels:
    app: UserApp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: UserApp


---


apiVersion: v1
kind: Service
metadata:
  name: point
  labels:
    app: point
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: point


---


apiVersion: v1
kind: Service
metadata:
  name: agreement
  labels:
    app: agreement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: agreement


---


apiVersion: v1
kind: Service
metadata:
  name: Benefits
  labels:
    app: Benefits
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Benefits

